# .travis.yml
#
# Setup for travis-cl.com
#
# @category  None
# @package   \
# @author    Rick Morice <rick@floor9design.com>
# @copyright Floor9design Ltd
# @license   MIT
# @link      https://github.com/floor9design-ltd/laravel-casts-uuid
# @version   0.1
# @since     0.1

language: php
dist: bionic
php:
  - '8.0'
  - '8.1.0'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - XDEBUG_MODE=coverage ./vendor/phpunit/phpunit/phpunit --coverage-text --coverage-clover=coverage.clover
  - ./vendor/bin/phpstan

after_success:
  - bash <(curl -s https://codecov.io/bash)